[package]
name = "gosub_rendering"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_html5 = { path = "../gosub_html5" }
gosub_styling = { path = "../gosub_styling" }
gosub_render_backend = { path = "../gosub_render_backend" }
taffy = "0.5.2"
anyhow = "1.0.86"
regex = "1.10.6"
rstar = "0.12.0"
