[package]
name = "gosub_svg"
version = "0.1.1"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"
description = "SVG rendering for Gosub"

[dependencies]
gosub_shared = { version = "0.1.1", registry = "gosub", path = "../gosub_shared" }
gosub_interface = { version = "0.1.1", registry = "gosub", path = "../gosub_interface", features = [] }
gosub_html5 = { version = "0.1.1", registry = "gosub", path = "../gosub_html5" }
tiny-skia = "0.11.4"
resvg = { version = "0.44.0", optional = true }
anyhow = "1.0.94"

[features]
resvg = ["dep:resvg"]
