[package]
name = "gosub_svg"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_html5 = { path = "../gosub_html5" }
gosub_render_backend = { path = "../gosub_render_backend" }
tiny-skia = "0.11.4"
resvg = { version = "0.44.0", optional = true }
anyhow = "1.0.94"

[features]
resvg = ["dep:resvg"]
