[package]
name = "gosub_webinterop"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
syn = { version = "2.0.82", features = ["full", "extra-traits"] }
quote = { version = "1.0.37", features = [] }
proc-macro2 = "1.0.89"
serde = { version = "1.0.210", features = ["derive"] }
lazy_static = "1.5.0"


[lib]
proc-macro = true
