[package]
name = "gosub_v8"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_webexecutor = { path = "../gosub_webexecutor" }
thiserror = "1.0.64"
v8 = "0.106.0"
anyhow = "1.0.89"
serde_json = "1.0.128"