[package]
name = "gosub_v8"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_webexecutor = { path = "../gosub_webexecutor" }
thiserror = "1.0.59"
v8 = "0.91.1"
anyhow = "1.0.82"
serde_json = "1.0.116"