[package]
name = "gosub_jsapi"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub-shared", features = [] }
uuid = { version = "1.7.0", features = ["v4"] }
regex = "1"
