[package]
name = "gosub_taffy"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_render_backend = { path = "../gosub_render_backend" }
gosub_typeface = { path = "../gosub_typeface" }
taffy = "0.6.1"
anyhow = "1.0.90"
regex = "1.10.5"
log = "0.4.22"
parley = { version = "0.2.0", default-features = false, features = ["std"] }
