[package]
name = "gosub_webexecutor"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
colored = "2.1.0"
derive_more = "0.99"
lazy_static = "1.4"
thiserror = "1.0.58"
v8 = "0.91.0"
anyhow = "1.0.82"
paste = "1.0.14"

[dev-dependencies]
serde_json = "1.0.116"
gosub_v8 = { path = "../gosub_v8" }
gosub_webinterop = { path = "../gosub_webinterop" }