name: GoSub Docs

on:
  push:
    branches:
      - main
      - docs-push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_DEPLOY_KEY: ${{secrets.SSH_DEPLOY_KEY}}
      - name: Rsync
        run: rsync -avz target/doc/ deploy@developer.gosub.io:/wwwroot/docs.developer.gosub.io/public
